### ISSUE TITLE
Komuso mines become invisible after use

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#103]
Submitter: Fungus
What I observed: After coming in contact with a komuso mine, it counts down and explodes normally. After the tile where the komuso mine is is scrolled off-screen and back on-screen again, the komuso mine respawns as expected, but is invisible, including the detonation animation. The resulting explosion from said invisible komuso mine is not invisible. What i expected: I expected the mine to respawn as a normal, visible block. NOTE: this issue is true with komuso mines placed on empty background space as well as mines placed inside solid floors.

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
