### ISSUE TITLE
Miscellaneous weapon bugs [0.9.2]

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#106]
Submitter: Samario
Rush Jet at 0 ammo can be used, but he just teleports away when it would normally tick down your ammo
rush bike can't be summoned even though you have 1 ammo left after it runs dry
jewel satellite and slash claw are cancelled early if you're next to a screen edge
sakugarne can be summoned at 0 ammo but teleports away instantly if you try to get on it
if you fire a tengu slash close to a screen edge and facing it, the projectile won't fire and you cannot move until you jump
power stone and flash stopper cannot be used when they have 1 ammo left
ice wall can crush the player against a screen boundary under certain conditions ( https://media.discordapp.net/attachments/466737266996543489/468171659237523457/icecrush.gif )

**Comment by snoruntpyro** [comment]
All fixed in version 0.9.3 (except for Ice Wall bug. File that as a seperate issue please. Not sure how to fix it)
