### ISSUE TITLE
.GBS & .NSF files are seen as both music and sound

### ISSUE THREAD

**Issue by RonanDuffy-InkTech** [MegamixEngine/MegamixEngine#107]
In the options menu, when you adjust the **MUSIC VOLUME** option, it works as intended; the currently playing music changes in volume while the sound effects remain intact.  However, the **SOUND VOLUME** option doesn't work as intended depending on the file type of the music currently playing.

If the file type is `.OGG`, then **SOUND VOLUME** works as intended; only SFXs change in volume, music does not.
But if it's a `.GBS` or `.NSF` file, then that too will change in volume along with the sounds.

I didn't get a change to test this with the `.SPC` or` .VGM` files present in the engine, but I'm guessing that they too would be seen as both music and sound.

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
