### ISSUE TITLE
Destroyable Tornado Blow/Break Dash/Black Hole Bomb Blocks not dying properly. 

### ISSUE THREAD

**Issue by srwolford** [MegamixEngine/MegamixEngine#109]
When a destroyable block is destroyed by Tornado Blow, Break Dash, or Black Hole Bomb, the block's collision is gone, but it continues to look like it's there. Also, the block will respawn when scrolled offscreen.

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
