### ISSUE TITLE
Gravity shenanigans with weapons

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#120]
Submitter: BBLIR
There are a few issues with gravity and weapons (v0.9.2);
- Magnet Beam doesn't display the main part of it (the actual beam) when you're upsidedown (the corners are fine)
- Water shield's, Jewell satelite's and Flame(?) mixer's sprites don't get flipped and so they look weird coming to normal gravity after coming from rev gravity. Also F.Mixer doesn't follow you with switching and thus it can go downwards
- Triple Blade's sprites are not upsidedown when you're upsidedown and it looks wrong
- when switching gravity, Search snake just dissapears
- when charging Pharaoh shot and flipping the fireball doesn't flip with you and thus ends up below you. Also when you release it, up is down and vice versa
- I don't think it makes sense for Rain flush to go downwards, even in rev grav
Also, not relevant, but Wire Adaptors's looking up sprites don't work.

**Comment by snoruntpyro** [comment]
All fixed in version 0.9.3 (except the last one. Idk what you mean by "it doesn't make sense", and Wire Adaptor sprites being missing is an issue I haven't figured out how to cleanly fix yet).
