### ISSUE TITLE
Hotheads and their aim (and lack thereof)

### ISSUE THREAD

**Issue by ACESpark** [MegamixEngine/MegamixEngine#122]
Hothead's shooting code assigns the xspeed to to the wrong object. It's currently assigning it to the Hothead itself, and not the Changkey.

The correct shooting code should be this:
``        with (a)
        {
        if (instance_exists(target))
            xspeed = xSpeedAim(x, y, target.x, target.y,yspeed,grav);
        }``

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
