### ISSUE TITLE
Objects call Draw/DrawBegin/DrawEnd for one frame before screen transition.

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#124]
This is relatively minor and easy to work around, may be unfixable on the engine layer for all I know, but it's a thing if you have an object that draws graphics.

Steps to reproduce:
1. Make a custom object that draws something to the screen based on the player's view. (primitives, text, etc.)
1a. Optionally print() something as well since it's easier to tell that it's just one frame in console.
2. Place it in any room other than the first.
3. Start the transition to that room. For one frame, you can see whatever it's meant to render flash and then disappear in the wrong room. It won't draw during transition, and then it'll act as intended while you're in the room it belongs to.

My dirty workaround is just to hook User Defined 15 (EV_SPAWN) and Create to set a bool to not draw on the next frame.

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
