### ISSUE TITLE
Jumping 3 tiles up onto objTopSolid while grinding edge of screen kills Megaman.

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#127]
Similar to a bug I filed three weeks later: https://github.com/MegamixEngine/MegamixEngine/issues/239

(whoops, meant objTopSolid in the title -and- video)

Is this an obscure bug or what...but it could potentially burn many entrants so...

Steps to reproduce:
1. Create a room with an objTopSolid at the edge, have it be 3 tiles above another objSolid/objTopSolid 
2. Head all the way to that edge of the screen (it works on both left and right), below your objTopSolid 
3. Depending on whether or not you hold (left if at left edge of screen, right if at right):
3a. If you don't hold left/right and jump fully up, Megaman won't die.
3b. If you do hold left/right and jump fully up, Megaman will die.

This doesn't happen if the objTopSolid is 1-2 tiles above where you're jumping from, but I haven't tested pixel-perfect short jumps. I'm not really skilled enough to.

Here's footage of the bug in action, easier seen than explained: https://youtu.be/Bmj-_zSA96E

**Comment by MightyPrinny** [comment]
fixed in dev branch
