### ISSUE TITLE
The Kamegoro Maker Whirlpool blocks don't work.

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#128]
Submitter: EvieMaybe, Trans Lesbian Extraordinaire
Email: hornetmaninc@gmail.com
they are worse than a tornado battery jeez theyre glitchy and the way they spawn is... odd? idk make them more viable and easy to stand on, my crops are dying

**Comment by snoruntpyro** [comment]
Iirc they only work in water (as that's how they worked in MM3). Are you making sure thats the case?

**Comment by snoruntpyro** [comment]
Idk why this is still open. They work fine.
