### ISSUE TITLE
[0.9.1] SuzyG fires two bullets in one direction instead of two opposite.

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#129]
Submitter: NBlast
Email: nblastmax@gmail.com
There is a bug in coding of SuzyG enemy. It spawns two bullets, but they go in the same direction instead in opposite sides.

Code makes sense at first with setting ID.dir in both 0 and 180 values, but it doesn't work. You can put values in like 45, 90 and 120 and it will only still shoot in half radius at max and never "behind". Tried to fix it on my own, but no success (GM beginner here).

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
