### ISSUE TITLE
Coswallowns can re-track Megaman

### ISSUE THREAD

**Issue by lnUniverse** [MegamixEngine/MegamixEngine#131]
Swallowns can respawn as long as the main bird has despawned, even if the attached Coswallowns are still onscreen. In Mega Man 4, the Swallown and Coswallowns simply would not spawn under these circumstances.

If you do this, when the Swallown launches the Coswallowns at you, existing Coswallowns from the same object will also be sent at you, even though they have already been sent. You can repeat this for infinite birds. 

![swallown](https://user-images.githubusercontent.com/41224946/43030284-42692c32-8c5c-11e8-8763-967c84ca59eb.gif)

I'd also like to note that the swoop this engine's Swallown does is much faster and shorter than it is in Mega Man 4, to the point that it almost feels like a different enemy entirely. And the angled-down frames the original Coswallowns have seem to be absent.

**Comment by MightyPrinny** [comment]
fixed in dev branch
