### ISSUE TITLE
That fish (from MM7, I guess?) doesn' t work

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#133]
Submitter: LanternCorp Yohltel
I think that I tested that on Test Room 4 of Version 0.9.2: that fish on the Mega Man 7 section of the test room, while in water, can end up leaving the map by going down.

**Comment by snoruntpyro** [comment]
Because it doesn't have block collision. It also only turns around in water after a specific point. So this issue isn't a bug. Closing for now.
