### ISSUE TITLE
i used the W tank in test room 5 (the one with the minibosses) and it crashed

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#14]
Submitter: Smedis2
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object objPauseMenu:

Push :: Execution Error - Variable Index [0,47] out of range [1,47] - -1.weaponVisible(103868,47)
 at gml_Object_objPauseMenu_StepNormalEvent_1 (line 112) -                         if (ceil(global.ammo[playerID, global.weaponHotbar[weaponVisible[i]]]) < 28)
############################################################################################

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
