### ISSUE TITLE
[Version 0.9.3] Flickering drop down menu in Game Maker Studio is prevent me from working on a level

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#143]
Submitter: ViperAcidZX
I was about to start working on a level in the Game Maker Studio program and I downloaded the latest version of the MegaMix Engine, but I'm having a serious problem with Game Maker Studio were the drop down menu for the assets keep flickering when I'm trying to access the titlesets (another folder has this issue too) and it's preventing me from doing any work from making a level. I'm using Game Maker Studio 1 1.4 provided in the main MegaMix Engine thread and the latest Git download of the MegaMix Engine (currently Version 0.9.3). I made a short screen capture of this issue here in a short video:  https://drive.google.com/open?id=1akAxWYa_CZsqIVB77_cG7hfl_IULL9Xc

**Comment by ACESpark** [comment]
There's _several_ topics, videos, and posts addressing this issue and why it happens. Several. Please read/watch one of them.
