### ISSUE TITLE
Fire Totem + Spark Shock visual error (0.9.3)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#144]
Submitter: William W.
Email: jwandzw@gmail.com
If a Fire Totem (Enemies > MM9 > objFireTotem) is hit by Spark Shock, it will correctly have an electric field surrounding it, but it will also turn blue, as it it was hit by Ice Slasher or the initial shot of Chill Spike.

**Comment by MightyPrinny** [comment]
fixed in dev branch
