### ISSUE TITLE
Setting respawn range to infinite makes things never respawn.

### ISSUE THREAD

**Issue by Entity1037** [MegamixEngine/MegamixEngine#151]
The intent is that something with a -1 respawn range spawns as soon as the section is loaded, but can still respawn if the entire section is left and reentered. The first part happens, but when trying to respawn for example junk blocks after destroying them, they never come back.

**Comment by MightyPrinny** [comment]
nevermind

**Comment by MightyPrinny** [comment]
I can't replicate this in dev branch
