### ISSUE TITLE
Setting despawn range to infinite makes objects not despawn properly when screen transitioning up / down.

### ISSUE THREAD

**Issue by Entity1037** [MegamixEngine/MegamixEngine#152]
![infinite despawn range glitch](https://user-images.githubusercontent.com/22569524/43171886-fc9be640-8f71-11e8-899c-cdd348450b7a.gif)

Works fine left / right though. Also made sure it's unrelated to the infinite respawn range issue (and vice versa).

**Comment by snoruntpyro** [comment]
I believe this is fixed in 0.9.4.
