### ISSUE TITLE
Asset Showcases - Designers Needed!

### ISSUE THREAD

**Issue by Flashman85** [MegamixEngine/MegamixEngine#154]
Like MaGMML2, the devkit for MaGMML3 will contain showcase levels that demonstrate the functionality of pretty much every object. Unlike MaGMML2, however, assets will be organized by theme, rather than by game. Now we need volunteers to design the showcases.

Each of these showcases already has a placeholder room created in the "showcase" branch of the devkit; all of the essential assets have already been placed in the room, but please add other assets as necessary to make things work (eg, rails for moving platforms). A few guidelines:

- Showcases should demonstrate as much potential as possible for each asset—things you can do with the creation code (eg, color variations), unique interactions with other assets (eg, lighting oil on fire), any functionality that isn't immediately obvious (eg, totem poles jumping when the player passes over them), etc.
- In general, try to introduce only 1-2 new assets per screen, so as not to overwhelm and distract the player; more assets can be introduced together if they share very similar functionality (eg, one screen with four variations of Shield Attacker is totally fine).
- Avoid using enemies and gimmicks that are showcased elsewhere; a little overlap is OK if necessary.
- Give the player frequent checkpoints and power-ups, and keep instant death to a minimum; the purpose is to give the player inspiration, not a hard time.
- No split paths or secret areas, please. Players should be able to go through the showcase once, see everything, and move on to the next showcase. If you feel your showcase is getting too long, let me know and we'll look at moving some assets into a new/different showcase.
- Leave a few screens' worth of open space on all sides of your showcase, in case more assets need to be added later.
- Use placeholder graphics until your level is finished and has been playtested. Once the design is more or less finalized, THEN decorate your level using the default tilesets included in the devkit. Try to limit yourself to just one tileset if at all possible, and keep the design simple. For the sake of time, consistency, and clarity, the focus should be on the assets; save your artistic skill for the actual contest.

Available showcases are listed below, with the room name in parentheses. If you're not on the devteam and want to help out, message me on Discord and we'll talk about the possibility of you joining the team. Otherwise, please edit this post and (1) add your name next to the showcase(s) you want to design, (2) list the tileset(s) you want to use, and (3) check the box when each showcase is finished. There's no concrete deadline yet, but the sooner these are finished, the better.

See the spreadsheet below for the most up to date list.:

https://docs.google.com/spreadsheets/d/1sQkdTw5gSkGHtG54SJM_F9j9Lg1BgBMtiHIXBVYtW-Y/edit#gid=0

**Comment by snoruntpyro** [comment]
Showcases are pretty much complete besides tiles so yeah
