### ISSUE TITLE
objSonicBill invisible upon respawn

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#164]
If allowed to activate and explode on its own, an instance of objSonicBill will be invisible when it respawns. Ideally, it should be visible.
Observed in Version 0.9.3.1.
Only affects Sonic Bills individually- one turning invisible will not cause others to turn invisible.
Does not affect hitboxes- Sonic Bills that are invisible can still damage and be damaged by Mega Man.
Destroying a Sonic Bill before it explodes prevents this behavior. Destroying an invisible Sonic Bill does not cause it to regain its sprite.

**Comment by snoruntpyro** [comment]
Fixed in 0.9.4.
