### ISSUE TITLE
fix for piledan turret

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#171]
Submitter: pieceofcheese87
Email: jdaneau87@gmail.com
in objPiledanTurret event user 0:
change line 14 to             var i = instance_create(x + 12 * image_xscale, y - 17 * image_yscale, objEnemyBullet);
change line 21 to             var i = instance_create(x + 12 * image_xscale, y - 27 * image_yscale, objEnemyBullet);

**Comment by MightyPrinny** [comment]
that is already fixed in the dev branch

**Comment by snoruntpyro** [comment]
Fixed in 0.9.4.
