### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#173]
Submitter: Quentin M Carpenter
Email: trufflesaurus@gmail.com
############################################################################################
FATAL ERROR in
action number 1
of Other Event: User Defined 14
for object objSuperArm:

array_set :: argument 0 is not an array
 at gml_Script_swap (line 9) - array[@ a] = array[@ b];
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_swap (line 9)
called from - gml_Script_quickSortBy (line 24) - swap(cmp, left, pivot_index);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Script_quickSortBy (line 47) - quickSortBy(array, cmp, pos + 1, right);
called from - gml_Object_objSuperArm_UserEvent14_1 (line 28) - quickSortBy(interactionCache, interactionCacheSort);

**Comment by snoruntpyro** [comment]
How did you trigger this?

**Comment by snoruntpyro** [comment]
Why is this still open lol
