### ISSUE TITLE
Quick Lasers do not continue moving after Ballade Missiles are destroyed

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#175]
Submitter: Stephen DiDuro
Email: sdiduro@gmail.com
If a Ballade Missile is used to block a Quick Man laser beam, the laser will not continue moving if the missile is destroyed and will act as if it's still being blocked.

**Comment by snoruntpyro** [comment]
Fixed in 0.9.4.
