### ISSUE TITLE
Dialogue Boxes and String Colour

### ISSUE THREAD

**Issue by ACESpark** [MegamixEngine/MegamixEngine#180]
Currently for dialogue boxes, the string colour pulls its palette from the NES colour table. This is a fine idea, but currently only takes one digit. This obviously, doesn't work when you want to choose one of the brighter colours. Replacing the code with the following works:
`var col1 = string_char_at(itext, i + 2);`
`var col2 = string_char_at(itext, i + 3);`
`var col3 = col1 + col2;`
`colour = global.nesPalette[real(col3)];`
`i += 3;`

**Comment by snoruntpyro** [comment]
Fixed in 0.9.4.
