### ISSUE TITLE
Ladders and Grav Lifts

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#181]
Submitter: YourFaceisintheMoney
Email: matthewrlamb99@gmail.com
When under the effects of a gravity lift, you can only grab onto ladders by pressing up. Pressing down won't let you on the ladder.

**Comment by snoruntpyro** [comment]
This is entirely intentional. No game in the classic series lets you grab ladders with the down key while overlapping them. I checked in MM9 Wily 3 to confirm this.
