### ISSUE TITLE
objToadRainCtrl Errors

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#185]
Submitter: Spin Attaxx
* The default blowSpeed value of -0.5 is far too strong for making jumps over bottomless pits while pushing against it. At that speed, I estimate the player may be able to jump three quarters of a tile, IF they're lucky.
* If there are two or more instances of objToadRainCtrl in a level, even if one is set to blow in the opposite direction, all instances blow the player in just one direction (this extends to entities like Nombrellan). This is despite the rain graphics correctly flipping to show the intended direction.
* The two objToadRainCtrl instances in rmTestHall2 do not push the player. At all.

**Comment by snoruntpyro** [comment]
Fixed in 0.9.4.
