### ISSUE TITLE
Sola fires it's laser in the wrong position under reverse gravity

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#189]
Submitter: Wishy Washy
Email: ClexYoshi@hotmail.com
https://cdn.discordapp.com/attachments/466737266996543489/472654874148995082/unknown.png This sola here on the ceiling shoots it's laser not from the bud but from two tiles underneath.  I know this is a relatively minor thing, I know... It should still probably be reported, though.

**Comment by snoruntpyro** [comment]
Fixed in 0.9.4.
