### ISSUE TITLE
Wave Man Pipes Flexibility

### ISSUE THREAD

**Issue by cratordavish** [MegamixEngine/MegamixEngine#194]
(woah, yeah we really can't catch everything...)
So, Wave Man Pipes can work through downwards screen transitions, but not upwards.
It doesn't at all work with horizontal screen transitions.

This seems very... "major" ?
Should we make this slightly more consistent with the way the engine is right now?

**Comment by MegamixEngine** [comment]
The actual problem is that you're probably putting solids over your pipes. For this reason, the game keeps crushing you during screen transitions. I will fix this, though.

**Comment by snoruntpyro** [comment]
Fixed in 0.9.4.
