### ISSUE TITLE
It is not possible to access Guts Man's stage in the example game

### ISSUE THREAD

**Issue by RonanDuffy-InkTech** [MegamixEngine/MegamixEngine#208]
When you get to the stage select in the example game, the following error gets printed across the screen in red:
`ERROR LOADING FILE, unable to hash file contents: Levels/lvlGutsMan.room.gmx`
If you actually try to select Guts Man, everything will seem fine until it's time to go to the stage, in which case it won't, softlocking the game.

This only happens in the example game; loading the level through `rmRoomSelect` works, and the level can be played.

**Comment by MightyPrinny** [comment]
fixed in dev branch
