### ISSUE TITLE
Wave Man Stream (a.k.a. Wave Man Steam) Fails to Hurt MegaMan and Obey The Laws of Time 

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#210]
Submitter: Fungus
I am using Version 0.9.4 (Beta). I observed that the steam does not hurt MegaMan. He can walk right through it. I also observed that neither time stopper nor flash stopper had any effect on this gimmick when used. I expected to observe the steam hurting MegaMan when he touched it. I also expected to observe the Wave Man Stream to become motionless whenever the time stopper or flash stopper weapons were active.

**Comment by MightyPrinny** [comment]
Fixed in dev branch
