### ISSUE TITLE
Can't bypass unnecessary keys in key config.

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#211]
This might belong as a feature request, but it's impossible to bypass unnecessary keys (slide, weapon left, weapon right) in key config. Why this might be a problem for some:

![retro_nes_controller](https://user-images.githubusercontent.com/3488391/43474442-e3505b22-94c0-11e8-8e0e-03b0c92cf1e5.jpg)

Let's face it...MAGMML attracts retro enthusiasts, so you can't discount the notion that a number of people will want to play on one of these...or something like it. Luckily for purely practical purposes, the default buttons are pretty accurate and it's possible to get slide assigned to SELECT for those couple of future levels which will surely force you to slide on a ladder. Have to close the game to do it though, as folks with such a retro controller essentially get trapped in the menus due to not having enough buttons to assign.

So FWIW, there's also a minor softlock attached to this as well.

**Comment by MightyPrinny** [comment]
Fixed in dev branch
