### ISSUE TITLE
(0.9.4) Boss healthbars are tied to the boss's image_angle variable

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#217]
Submitter: Giest118
Email: giest118@gmail.com
The objGlobalControl object's Draw event has lines of code for drawing sprHealthbarBackground, and for reasons that elude me, these draw commands use image_angle for their angle. As a result, if the boss's sprite rotates, so will the lifebar. Is this intentional?

I would think the angle these are drawn at should be hard-coded as 0, in line with the commands that draw sprHealthbarSecondary.

**Comment by MightyPrinny** [comment]
fixed in dev branch
