### ISSUE TITLE
Metal Man reacts to conveyer belts (He shouldn't)

### ISSUE THREAD

**Issue by RonanDuffy-InkTech** [MegamixEngine/MegamixEngine#220]
If you place a MM2 conveyer belt over a boss arena, and place Metal Man inside it, he will be affected by the conveyer.
![megamixmetalmanbug](https://user-images.githubusercontent.com/35691333/43679729-5942962e-9822-11e8-8aec-1eb70fa007a8.gif)
This is not accurate to his behaviour in MM2, where he always stays in place until attacking, conveyer underneath him or not.

I do believe that the ability for him to be moved by the conveyers could be allowed as an option though.

**Comment by MightyPrinny** [comment]
Fixed in dev branch
