### ISSUE TITLE
Buster shots make "splash" sound at edge of screen in water area. (under common conditions)

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#228]
https://www.youtube.com/watch?v=h0d73e0LiRI

On the right side, the water collision ends at section's edge. On the left side, the water collision extends two tiles left of the section's edge. That's the workaround...but overall buster shots shouldn't really be doing that...

Here's the room for testing:
[lvlSarysa_WaterBusterBug.room.zip](https://github.com/MegamixEngine/MegamixEngine/files/2264319/lvlSarysa_WaterBusterBug.room.zip)

**Comment by lnUniverse** [comment]
Objects crossing the left and top boundaries of water only produce a splash when entering the water. In contrast, on the right border objects make a splash when exiting the water as well as the one made when entering. This is what causes the splashes when projectiles exit the right side of a screen with water.
In addition, objects crossing the bottom boundary only make a splash when moving downwards, and even then it failed to happen at certain speeds.

**Comment by sarysa** [comment]
Yep, but it's pretty offputting. I would imagine that checking if the boundary >= global.sectionRight or <= global.sectionLeft and not playing the sound if so would keep it from happening, though I haven't dug very deep into this.

**Comment by snoruntpyro** [comment]
oh whoops this was fixed forever ago, never closed this
