### ISSUE TITLE
Weapons and gimmicks breathe underwater

### ISSUE THREAD

**Issue by lnUniverse** [MegamixEngine/MegamixEngine#235]
Many weapons and gimmicks release bubbles from their origin when used underwater despite them being clearly inanimate. This looks especially odd on Time Stopper, with bubbles spawning in the precise center of the screen frequently while time is stopped. It's also fairly visible with Concrete Shot, Ice Wall, Gemini Laser, Chill Spike, and Super Arrow.

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
