### ISSUE TITLE
Potential memory leak with Air Man

### ISSUE THREAD

**Issue by RonanDuffy-InkTech** [MegamixEngine/MegamixEngine#238]
In Air Man's code, data structures are used; specifically **DS grids**.

Four are created in the *create* event:
![AirMan_CreateEvent](https://user-images.githubusercontent.com/35691333/43996675-c36c1fd2-9dbf-11e8-8e8f-04375d9d5338.png)

But in both the *destroy* event and the *room end* event, only three of them get destroyed:
![AirMan_DataStructureDestroy](https://user-images.githubusercontent.com/35691333/43996712-842656a2-9dc0-11e8-8200-6d520a3173f0.png)

Since data structures need to be destroyed when not in use, so as to free up the memory used, using Air Man can lead to memory leaks.

**Comment by ACESpark** [comment]
Fixed in dev branch.
