### ISSUE TITLE
Bubble Man shots stuck in walls

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#244]
Submitter: JamesVidkophf
Email: gamtrooperx@gmail.com
I decided to have bubble man as a boss. As I was fighting him I noticed his normal shots (not bubble lead) were getting stuck in the walls. They never fully scrolled off screen. Not too dangerous I think but concerning all the same.

**Comment by snoruntpyro** [comment]
This was fixed ages ago - not sure why this is still open.
