### ISSUE TITLE
Unintuitive inversion of vertical axis controls when gravity is flipped

### ISSUE THREAD

**Issue by lnUniverse** [MegamixEngine/MegamixEngine#247]
- [x] Some weapons aim unintuitively when Megaman is in reverse gravity. Pressing the UP button causes Megaman to counterintuitively fire them downwards.

Weapons up and down are reversed for:
Tengu Blade (and sliding in general)
Metal Blade
Pharaoh Shot
Magic Card
Rush Bike

Weapons up and down remain normal for:
Rush Jet
Black Hole Bomb

Ideally, most weapons would aim downwards when you hold down no matter what way Megaman is facing.

Rush Bike and Sliding make sense to be inverted when gravity is swapped, since you push towards the ground. Rush Bike is debatable, though.

Salt Water 'remains normal' in that the arc produced by the up and down directions are the same ones produced in normal gravity, but it should probably be inverted when upside down since the arc is based on the (now inverted) gravity.

Additionally, under reverse gravity:

- [x] Thunder Wool gets stuck on the floor
- [x] Hornet Chaser moves the wrong direction vertically
- [x] Wheel Cutter gets stuck in corners
- [x] Sakugarne goes significantly deeper into the terrain
- [x] Block Drop spawns near the top of the screen and then falls up, making it much harder to use
- [x] Rain Flush produces rain from the top of the screen even though the capsule flew to the bottom

**Comment by snoruntpyro** [comment]
Fixed on dev branch. I went with inverting all controls since IMO it makes more sense. I couldn't get Block Dropper to work properly so I just made it have no difference between gravities.
