### ISSUE TITLE
objTornadoPlatformStop does absolutley nothing (Version 0.9.4 Beta)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#252]
Submitter: Yoshiatom
objTornadoPlatformStop has no effect on objTornadoPlatform's movement; for example trying to use the object in place of objRailBumper just causes the platform to fall off of the rail when it reaches it.

**Comment by MightyPrinny** [comment]
this object no longer exists in the dev branch
