### ISSUE TITLE
Heat Man collision bug (0.9.4)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#254]
Submitter: William W.
Email: jwandzw@gmail.com
I have found a collision error involving Heat Man.
Pictured below is a single-screen room, with the boss door tiles having their collision set via the ObjectSetter, and the other tiles having their collision set via individual objSolid objects. After triggering Heat Man's charge attack via damaging him, then making him stop while Mega Man is directly against either wall, Heat Man gets stuck inside the wall. While he is in the wall, his flame projectiles do not react to the floor of the room at all, but do react to the wall. Making Heat Man charge again while further from the wall frees him, and his flame projectiles began functioning normally again.
However, making him charge into a wall while he's already stuck in the wall causes him to go even higher, and repeating this enough times causes him to fly above the screen, causing him to only be reachable using certain weapons. Getting Heat Man stuck in a wall more than once in a row seems to make his fire projectiles function normally again.
If I try to make him stay in the same wall by lingering directly under him, the result varies: the first time I attempt such, he moves upwards slightly (similar to what happens when he gets stuck from switching between the two walls), but if he faces away from the wall, he will fall out of it. Attempting to make him rise even higher will simply result in him charging out of the wall, and the battle will continue normally.
I did not expect Heat Man to get stuck in the wall at any point, nor did I expect his flames to briefly have bugged collision. I simply expected him to stop far enough from the wall that he wouldn't get stuck in it.
Everything here has been tested using both single-tile versions of objSolid and resized versions of the same object. In the latter case, five objSolid objects were used, with varying sizes (calculated by how many 16x16 squares the object covered): one 14x2 object (the floor), one 1x14 object (the right wall), one 14x1 object (the ceiling), and two 1x5 objects (the sections of the left wall that were not made of boss door tiles).
https://i.imgur.com/9A0wZe2.png

**Comment by MightyPrinny** [comment]
Fixed on dev branch
