### ISSUE TITLE
Some projectiles don't get reflected by Jewel Satellite

### ISSUE THREAD

**Issue by RonanDuffy-InkTech** [MegamixEngine/MegamixEngine#257]
One of the aspects of Jewel Satellite is that projectles, if allowed to, can be reflected back. The problem is that some do not when they are most likely meant to; instead, they just phase through Mega Man and the shield.

When I look in the coding of a projectile that usually behaves this way, they usually have these lines of code in their Step Event:
```
xspeed = cos(degtorad(dir)) * 1.5 * xscale;
yspeed = -sin(degtorad(dir)) * 1.5;
``` 
My guess is that Jewel Satellite changes the projectile's speed, but its speed gets 'reset' by those lines.

What I noticed is that whoever coded `objBeakBullet` was aware of this, as they not only coded a workaround but also acknowledged it in a comment:
```
if (xspeed == 0 && yspeed == 0) // If we set it every frame, besides being useless it won't be reflected by jewel satelite
{
    xspeed = cos(degtorad(dir)) * 3 * xscale;
    yspeed = -sin(degtorad(dir)) * 3; // yspeed needs to be inverted to match the coordinate system
 }
```

Here is a list of enemy projectiles that exhibit this bug that I have discovered thus far (funnily enough, they're all Met projectiles):
- [ ] objMM1MetBullet
- [ ] objMM3MetBullet
- [ ] objMetallDXBullet
- [ ] objMM4MetBullet

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
