### ISSUE TITLE
Tiles flipped over Y axis don't show as flipped through objRevealingTiles (v 0.9.4)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#258]
Submitter: KamikazeScotsman
When you flip a tile over its Y axis, it shows up correctly in the editor, but when the game is running and an objRevealingTiles in the room, it's upside down (in its natural orientation).

**Comment by ginger-mochi** [comment]
Fixed in 09bfbd3f, along with some other objRevealingTiles errors.
