### ISSUE TITLE
Glooper & its gloop

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#263]
Submitter: Cheez!
-Killing a Glooper whose shot is still on-screen and then standing where the Glooper used to be will result in Mega Man somehow getting hit by the shot.
-If you stand in the same place as a Glooper BEFORE killing it, it seems to take one last shot and then stop firing forever.
-If Mega Man does a screen transition while affected by a Glooper's gloop, the effect (minus the damage) persists. The gloop vanishes though, and with nothing else to overcome, Mega Man is instead doomed to a futile struggle against the universe itself. He'll be stuck unable to jump, shoot, climb, etc. until he either dies or gets hit by more gloop.

All observed in v0.9.3.1

**Comment by ACESpark** [comment]
Fixed on dev branch.
