### ISSUE TITLE
Fire Pillar hitbox bug

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#266]
Submitter: Samario
The Fire Pillar's hitbox moves downwards when retracted instead of shrinking, being able to hit players underneath the block that the pillar is placed on; either the graphic shouldn't disappear to indicate the hitbox is now below the block, or the hitbox should shrink instead of moving downwards so that Mega Man cannot be hit by nothing while underneath the block

**Comment by cratordavish** [comment]
I believe that's a thing you can do in MM1 as well. So it's there to just be accurate to the source material.

**Comment by Samario1** [comment]
okay, but while that might be the case, the graphic disappears in the devkit, while it doesn't in MM1, so it's a bug either way

**Comment by snoruntpyro** [comment]
Fixed at some point in 1.0.0 or beyond.
