### ISSUE TITLE
Flame pillars cannot be frozen while Magma pillars can...?

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#267]
Submitter: Cut Man For The 3rd Time
Email: wishthen@gmail.com
In MM1,Ice Slasher could freeze Flame pillars.This goes for Concrete Shot + Magma pillars in MM9 As Well.
But In The Megamix Engine,Ice Slasher,Concrete Shot And Ice Wall can freeze magma pillars,But none of those (Or Anything) can freeze flame pillars,not even ice slashers.
This seems REALLY Inconsistant and should really be changed to be completly honest.

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
