### ISSUE TITLE
Claws crash on level load if in room with additional enemy

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#270]
Submitter: NARFNra
If you try to open and play a level containing a room with a Claw and another entity (even another Claw) in it, the level will crash and return out a message like this.
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Create Event
for object objClaw:

Variable objClawSpawner.dead(100105, -2147483648) not set before reading it.
at gml_Script_checkSolid
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_checkSolid (line -1)
gml_Object_objClaw_Create_0

Tested with: Claw Spawner, Feeber, Claw, BokazurahPlatform

**Comment by MightyPrinny** [comment]
Fixed on dev branch
