### ISSUE TITLE
Screen not scrolling 

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#272]
Submitter: Starheart
Email: Tdayx06@gmail.com
My problem is that in a level i was creating the screen wouldnt scroll even though i had The screen Scrolling Things

**Comment by snoruntpyro** [comment]
Did you copy your room from lvlCopyThisRoom?

**Comment by ACESpark** [comment]
Can you confirm_how_ you are using the scroll objects. Bare in mind they are boundaries.

**Comment by snoruntpyro** [comment]
Why is this still open
