### ISSUE TITLE
Rush Cycle softlocks Mega Man on a Maze Warp.

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#286]
![rush_surf](https://user-images.githubusercontent.com/3488391/44826166-ccfb2a00-abdb-11e8-9a5f-8bc84ed08028.gif)

Easy-ish to reproduce. Just make an objMazeWarp transition and get onto Rush Cycle before it. Upon transition the cycle vanishes and Mega Man keeps the xspeed going, losing all control. Can be hurt by enemies and pits, but not spikes.

Map for reproducing:
[lvlSarysa_RushBikeSoftlock.room.zip](https://github.com/MegamixEngine/MegamixEngine/files/2334403/lvlSarysa_RushBikeSoftlock.room.zip)

**Comment by snoruntpyro** [comment]
Fixed on dev branch.

**Comment by Riguor** [comment]
@snoruntpyro Apparently the fix either was incomplete or was overwritten, was messaged today that this bug is in the latest dev branch version of the engine.
