### ISSUE TITLE
Normal solids become spikes or ice

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#287]
This bug occurs in MegamixEngine/master and MegamixEngine/dev as of 2018-08-30.

My MaG48HMML entry experiences a bug in which ordinary solid surfaces behave strangely in places, acting like spikes or ice when they shouldn't. Spikes appear at the approximate coordinates (2752, 416), (3008, 1072), and (3200, 1264), and ice appears at (2784, 272).

Below is the link to my entry, the same files that I submitted to the contest. Please don't click this link if you're a MaG48HMML judge.

https://www.dropbox.com/s/5q65yp7jb2zexyt/BuggyLevel.zip?dl=0

In order to keep my entry secret, I originally reported this bug on the submission form and in a README in the file that I submitted. According to the submission-tracking spreadsheet, however, my level has already been inserted into Judge EXE 4. I want to make sure this bug is fixed in that EXE, or at least sidestepped in my case, since the invisible spikes make Kaizo traps out of several of my level's screens.

**Comment by MightyPrinny** [comment]
its not a bug, its a problem with your level, your object setter setup doesn't have the entire tileset and you used tiles that weren't in that chunk with the object setter
