### ISSUE TITLE
Maze Warp / Water Shield interaction error, WS lost and lingers

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#289]
https://www.youtube.com/watch?v=21BxAq8U0Z8

Easily reproduced on one of my other Maze Warp error maps. Unspent Water Shield projectiles seem to linger forever, and doesn't follow the player through a Maze Warp.

(which, by the way, is likely to be fairly common not as a gimmick, but for the sake of segmented design...since GM lacks any bulk copy/paste function)

In any case, the video shows how this could end up being a bit odd/confusing for players.

**Comment by sarysa** [comment]
So the "lingers" half of this may be a <= 0.9.3.1 issue, since shiftVisible was fixed in 0.9.4. Whether or not the "projectiles lost" aspect is important is up to you guys to consider to be important or not.

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
