### ISSUE TITLE
Mega Man stands up into spikes when he's on solids.

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#293]
![dynamic_solid_vs_spike](https://user-images.githubusercontent.com/3488391/44963837-2bd1e380-aefb-11e8-946b-2d9fa5f92326.gif)

I had this happen with some custom code so I tested with MM2 falling platforms and the block trains seen above, and it seems to be an engine issue. Solids created dynamically or belonging to objects don't seem to prevent Mega Man from standing up while sliding under spikes.

This map for testing has both cases I listed. (and a boss door to nowhere)

[lvlSarysa_DynamicSolidSpikeSlide.room.zip](https://github.com/MegamixEngine/MegamixEngine/files/2343960/lvlSarysa_DynamicSolidSpikeSlide.room.zip)

**Comment by sarysa** [comment]
Scratch the "dynamic" part...seems to happen even with normal solids. Is this intentional?

**Comment by MightyPrinny** [comment]
As far as I now only mega maker allows you to slide through spikes like that

**Comment by MightyPrinny** [comment]
Fixed on dev branch
