### ISSUE TITLE
Twin Shooter S cannot have its image_yscale changed in the editor

### ISSUE THREAD

**Issue by RonanDuffy-InkTech** [MegamixEngine/MegamixEngine#297]
To change the starting direction of a _Twin Shooter S_, you have to change its image_yscale. You are told to do this in the **room editor**.
However, setting the yscale that way doesn't make Twin Shooter change starting direction, but setting it in the instance's **creation code** does.
I believe the problem is that in the _Creat Event_, its image_yscale is set to one, and it would seem that changes done through the editor occur before an object's creation event.

**Comment by MightyPrinny** [comment]
thats not a bug, his movement pattern is in an array, you're only told to change image_xscale

**Comment by RonanDuffy-InkTech** [comment]
Array?
Are you sure you're not thinking of Twin Shooter G (the big midboss cannon)?
I'm talking about the smaller enemy version.

**Comment by MightyPrinny** [comment]
oh oops

**Comment by snoruntpyro** [comment]
Fixed at some point in 1.0.0 or beyond.
