### ISSUE TITLE
crash error regarding objPUSwitchBlockRed

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#306]
Submitter: RoyKirbs
Game immediately crashes on room load if any Switch Block-related object is in it. Error log below.

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object objPUSwitchBlockRed:

trying to index a variable which is not an array
 at gml_Object_objPUSwitchBlockRed_StepNormalEvent_1 (line 5) -     if ((global.flagParent[myFlag].active && object_index == objPUSwitchBlockRed)
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Object_objPUSwitchBlockRed_StepNormalEvent_1 (line 5)

**Comment by snoruntpyro** [comment]
https://www.youtube.com/watch?v=yrtEkzzv4NY&index=5&list=PLOAMF_ipmHUfgCL2rM5BBnmhWPGla7WOl&t=0s
