### ISSUE TITLE
[devkit] NSF music stutters on level launch and when changed programmatically.

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#308]
This bug wasn't present in 0.9.X. Easy to witness in the default levels, whenever an NSF track starts it stutters. When it's changed programmatically within a level, it's far worse...starting briefly, stopping for about 15-30 frames, and then starting again in earnest.

This doesn't happen with OGG.

**Comment by snoruntpyro** [comment]
this was definitely present pre-1.0.0 its just the music player + gms being bad.. just restart i guess, closing for now unless this is actually somehow something we caused

**Comment by sarysa** [comment]
As mentioned in Discord, it happened every time I ran the game...probably did so around 30 or so times. (had a lot to debug)
