### ISSUE TITLE
Expand Rock...IS ALIVE!!!

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#310]
Submitter: Nintega94
So...Analog Stick on controller is still wack. 1st off, Megaman doesn't move on the ground if used with analog stick, but if u jump, he moves at double speed. On top of that, Sliding with Analog Stick will still have Megaman Grow Wide like in 0.9.1. so yeah, EXPAND ROCK IS STILL ALIVE

**Comment by snoruntpyro** [comment]
SHOULD be fixed on dev branch.
