### ISSUE TITLE
Simultaneous keyboard+controller input allows jumping/sliding twice as fast

### ISSUE THREAD

**Issue by hollowaytape** [MegamixEngine/MegamixEngine#317]
I noticed if you hold a horizontal arrow key and a controller directional input at the same time, you are prevented from walking, but you jump and slide twice as fast. You can jump/slide twice as far as a result. And the sliding sprite gets horizontally stretched twice as wide.

![megamix_double_input2](https://user-images.githubusercontent.com/4776099/45776487-03e3bf00-bc21-11e8-9284-0bfef959f058.gif)

It seems like an obscure input, but I found this when I forgot to turn off JoyToKey for MaG24HML.

Reproduced this in 1.0.1 and 1.0.2, haven't tried others. This doesn't occur in the MaGMML2 release.

**Comment by snoruntpyro** [comment]
This SHOULD be fixed on dev branch.
