### ISSUE TITLE
Bosses aren't affected by Scale X

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#32]
Submitter: Yoshiatom
If you scale a boss in Game Maker's room editor, it's X dimentions won't be affected either visually or hitbox-wise, while scaling by Y works fine.

**Comment by MightyPrinny** [comment]
you're not supposed to scale anything

**Comment by MightyPrinny** [comment]
Its not a problem with bosses in general, you can code a boss that can be scaled in the editor, it really depends on the implementation of each boss

**Comment by ginger-mochi** [comment]
There is not intended to be any support for non-unit instance scaling. Use this at your own risk. Closed as `wontfix.`
