### ISSUE TITLE
Rush Cycle with infinite ammo acts weird.

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#320]
Submitter: It's a secret to everybody. Especially judges.
When MM is hit it briefly shows a bar of ammo missing. Also if MM is on spikes it will spam hit noises even though he's invincible. Maybe change this?

**Comment by snoruntpyro** [comment]
Fixed on dev branch. Now, Rush Cycle spends health instead of weapon energy in these situations if energy is infinite.
