### ISSUE TITLE
Colton fires every frame while partically offscreen. (vertical free scrolling)

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#321]
https://www.youtube.com/watch?v=G5rpiQYGK0E

If Colton is on a Vertical free scrolling section, he'll fire every frame if he's at a Y where he doesn't despawn, but his bullet does. Same goes for using respawnRange/despawnRange -1. Makes a nasty lawnmower sound as well, since the sound restarts every frame.

p.s. that's not my contest level in the video.

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
