### ISSUE TITLE
[1.0.2] Bari III and their sound waves are inaccurate

### ISSUE THREAD

**Issue by Zieldak** [MegamixEngine/MegamixEngine#323]
In the original game, the sound waves travel with a much different angle, and they desapwn shortly after they touch the ground the second time. Also, the Megamix Bari III doesn't sink into the floor like it should.
Also, chaos fantazy is a nerd Today at 5:12 PM
aaa the megamix one’s column thing is flipped
The Bari III pillars always face right, and don't turn when the head does either.

Edit: Btw this is how you test enemy behavior properly.

Comparsion videos:
https://cdn.discordapp.com/attachments/446385132689948683/492697227223891968/mm10.mp4
https://cdn.discordapp.com/attachments/446385132689948683/492697272350539786/megamix.mp4

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
