### ISSUE TITLE
[1.0.2] objMetallJump inaccuracies

### ISSUE THREAD

**Issue by Zieldak** [MegamixEngine/MegamixEngine#325]
In MM6, if it jumps into a wall it bounces back like Power Musclers do.
In this engine, it doesn't, and he's also unable to jump over obstacles it otherwise could if it's touching a wall, even though it clearly jumps high enough.

**Comment by MightyPrinny** [comment]
Isn't Metall Jump from MM4?

**Comment by Zieldak** [comment]
Now that you mention it, the MM6 version of the Metall Jump is nowhere to be found in the engine. MM6 has it's own variation of the Metall Jump, which is only spawned by the Metall Pottom if I remember right.
It jumps a very short distance (it lands exactly on the second block in front of it) and never alters it's jump height like MM4's does, and shoots exactly when it jumps.
