### ISSUE TITLE
[1.0.2] Certain enemies can't jump over obstacles that they can in the original games

### ISSUE THREAD

**Issue by Zieldak** [MegamixEngine/MegamixEngine#326]
Certain enemies don't retain their horizontal movement speed after hitting a wall, making them unable to jump over obstacles they could otherwise easily jump over, not even one block high solids. This affects enemies including but not limited to: ReturningMonkey, Monking, Hopps^1, Bikki, PetitCroaker, MM2Mech, SpringFaceBomb, MetallJump^2.

PetitCroaker example: https://cdn.discordapp.com/attachments/466737266996543489/492785449253732373/1.gif

^1 untested in original game
^2 this appears already in an other issue

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
