### ISSUE TITLE
[1.0.2] Pressing L and R at the same time in the pause menu

### ISSUE THREAD

**Issue by Zieldak** [MegamixEngine/MegamixEngine#328]
Pressing L and R at the same time in the pause menu plays a confirmation sound, but doesn't actually quick select the Mega Buster. It either should do that or shouldn't play that sound effect.

**Comment by snoruntpyro** [comment]
This isn't what this does. If you press L and R, the weapon order is reset to the default order. It's not meant to be a buster quick select.
