### ISSUE TITLE
[1.0.2] objBrown missing features

### ISSUE THREAD

**Issue by Zieldak** [MegamixEngine/MegamixEngine#333]
In MM6, its container acts as solid ground and it's possible to jump on the little bumps on the sides too, and it's also possible to jump on top of it, however colliding with it damages the player. If the player collides with the container and he isn't attacking with bullets, his head also pops up, facing the player, unless the player is hogging the barrel in which case he faces the opposite direction (which may be a result of a bug in the original game)
The Megamix engine version **lacks all of these** features.

**Comment by snoruntpyro** [comment]
Fixed on dev branch. (except that weird behavior you said was probably a bug. probably not worth it.)
