### ISSUE TITLE
[1.0.2] objBuildingPlatforms unable to assemble after they disassemble

### ISSUE THREAD

**Issue by Zieldak** [MegamixEngine/MegamixEngine#334]
After the Building Platforms disassemble and are respawned, they will be unable to assemble again. Not even going into an other section and returning fixes this issue.

Showcase: https://cdn.discordapp.com/attachments/466737266996543489/492790899089342474/1.gif

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
