### ISSUE TITLE
Issue with Screen scrollers

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#337]
Submitter: Xlsfd
Whenever I use ObjRightScrolling, ObjLeftScrolling or ObjHorizontalScrolling, the level freezes, the screen shifts the view down 4-5 tiles and begins shaking up and down when Megaman should trigger the scrolling of the visible screen. Nothing short of terminating the player window with ESC works. ObjStopScrollingHorizontal does work as intended. I didn't test whether or not this bug also occurs with vertical scrolling, but I presume it does. Removing the scrolling objects from my level does fix the bug, but it makes the screen scrollers effectively unusable.
The version of the engine is 1.0.2m3, which is the current engine at the time of this writing. I did follow snoruntpyro's tutorial video and copied my room from lvlCopyThisRoom. I don't know if it's important, but I am using the ObjSetter/Autotiler in conjunction with a custom tileset.

**Comment by snoruntpyro** [comment]
Please show your entire room.

**Comment by Xlsfd** [comment]
[MagMML 3 Bug.zip](https://github.com/MegamixEngine/MegamixEngine/files/2410834/MagMML.3.Bug.zip)

Here you go. It contains a basic room where the bug happens, the tileset file and the tileset image file.

**Comment by Xlsfd** [comment]
The bug seems to be fixed in the new 1.0.3 release. Thanks^^

**Comment by snoruntpyro** [comment]
OK
