### ISSUE TITLE
[1.0.3m3] Tiles will randomly disappear when you upload maps from previous versions.

### ISSUE THREAD

**Issue by lizardcommando** [MegamixEngine/MegamixEngine#342]
I uploaded a map I created in the previous version of the engine [1.0.2m3] and some of the tiles had disappeared. Placing tiles back in the map would sometimes make certain tiles disappear, place a random tile somewhere on the map. I would sometimes not be able to place any tiles on the map at all.

**Comment by MightyPrinny** [comment]
we can't fix this, its a game maker bug and can happen in the same version as well
