### ISSUE TITLE
Tiled just crashes whenever I try to turn off certain weapons.

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#348]
Submitter: Tyler Dixon
Email: tldjjn@gmail.com
Basically, I did exactly what you'd do in Game Maker, set the weaponsettings object and put in "global.weaponLocked[global.weaponID[? objSparkChaser]] = true" in the creation code just to test, however when I ran it via the executable it just caused a fatal error, specifically:

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Other Event: Room Start
for object objExternalRoomSetup:

trying to index a variable which is not an array
at gml_Script_getInstanceVariableArray
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_getInstanceVariableArray (line -1)
gml_Script_parseExpression
gml_Script_stringExecutePartial
gml_Script_roomExternalSetupPost
gml_Object_objExternalRoomSetup_Other_4

Now that could just be my lack of knowledge about Game Maker and Tiled capabilities compared to it, but, it works just fine for my friend, who uses Game Maker, but I can't so I use Tiled. Is it just unfixable? Is it Tiled? If it is, that'd really suck, since certain weapons make the level I'm working on a breeze, so, if anyone has any answers, uh, please help.

**Comment by MightyPrinny** [comment]
use setWeaponLocked(objWeapon,true/false)

**Comment by MightyPrinny** [comment]
Just to clarify, this happens because when you run the level in tiled, your room is loaded externally(this is a feature of megamix engine) and creation code is run via string code execution which is not fully featured, luckily all of these weird game maker notations have a function that does the same thing, but in this case you don't need that because we also have a script to lock weapons.
