### ISSUE TITLE
attacked by Plant Man and crashed (LIGHTWEIGHT VERSION)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#349]
Submitter: Smedis2

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Other Event: User Defined 8
for object objPlantBarrierBoss:

Variable objPlantBarrierBoss.objFlameMixer(104105, -2147483648) not set before reading it.
 at gml_Object_objPlantBarrierBoss_UserEvent8_1 (line 2) - if (other.object_index == objFlameMixer)
####################################################################

**Comment by snoruntpyro** [comment]
Fixed on current lightweight branch
