### ISSUE TITLE
Break Blocks Break from Uncharged Break Dash

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#351]
The Break Dash specific destroyable blocks break from a shot of the uncharged Break Dash. Not necessarily a glitch, but I think it's an oversight worth mentioning which limits the potential of said blocks. I expected only the charged Break Dash, the actual dash, to break these blocks

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
