### ISSUE TITLE
Git Reports Issue

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#357]
Suddenly when running the light version of the engine, 1.0.31l I started getting the following error message when trying to compile the engine through 'Run the Game':

############################################################################################
FATAL ERROR in
action number 1
of Create Event
for object objObjectSetter:

global variable name 'warningLevel' index (100285) not set before reading it.
 at gml_Script_print (line 49) - if (global.warningLevel <= warningLevel)
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_print (line 49)
called from - gml_Object_objObjectSetter_CreateEvent_1 (line 10) -     print("Autotile begin (instance " + string(id) + ")", WL_VERBOSE);

Last night I compiled the engine without issue. This morning I am stopped by that message, the only change I made before that was changing the sprite on an NPC, nothing was touched in the object setter.

This error occurred to me before with an earlier version of the Magmml3 build. Ultimately, using a fresh install of engine worked then, though that's certainly an imperfect solution.

**Comment by MightyPrinny** [comment]
This happens when rmInit is not at the top of the room list
