### ISSUE TITLE
Concrete Man Up Platform turns invisible after leaving screen and coming back

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#358]
Submitter: Brandon
As the title states, this issue is happening in version 1.0.3.1 of the engine, and only seems to affect the Up platforms, not the Down ones, to my knowledge. I haven't extensively tested it, but here's a setup that should be reproductible: put an Up platform in a square, as well as a ladder somewhere that allows you to go off screen vertically, and then back. Step on the platform to send it flying up, scroll to the other screen, and then come back. If my testing is correct, the platform will still be in its original place, but will now be invisible. This surprised me, because I know for a fact that this did not happen in the Magmml2 engine, as I am recreating a setup I had initially conceived there.

**Comment by MightyPrinny** [comment]
fixed on dev branch
