### ISSUE TITLE
[1.0.3.1] objElecBlock ignores @cc delay if Mega Man spawns in the same screen

### ISSUE THREAD

**Issue by Lord-Saturn** [MegamixEngine/MegamixEngine#359]
Setting a certain delay for both objElecBlock and objEleckBlockRotatable works as long as Mega Man has not spawned in that screen, otherwise the variable is ignored. 

[https://orig00.deviantart.net/75e0/f/2018/271/e/1/megamixelecblockdelay_by_irregularsaturn-dco1ry7.gif](url)
Values in that gif:
waitLenght = 180;
delay = 0,60,120 (respectively)

**Comment by MightyPrinny** [comment]
fixed on dev branch
