### ISSUE TITLE
No sliding on 1 tile gaps?

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#360]
Submitter: LanternCorp Yohltel
Mega Man seems to be unable to slide through 1 tile gaps, while, at least at the GB games, he could.

**Comment by snoruntpyro** [comment]
What do you mean "1-tile gap"?

**Comment by LanternCorpYohltel** [comment]
This:
https://imgur.com/a/fFGU5oG

**Comment by snoruntpyro** [comment]
The intended behavior is for MM to slide over this gap. This is how sliding behaves in every single numbered classic game as far as I'm aware (besides 1 and 2 obviously).

**Comment by sarysa** [comment]
I'm running 1.0.0m3 with just 1.0.1m3 collision fixes and a couple other random imports from later devkits, and sliding over 1-tile gaps seems to work fine. There's a fairly key one in a side-level I've worked on (not a contest entry) and I've never fallen through it in a slide in either direction.

**Comment by snoruntpyro** [comment]
Dunno why this is still open.
