### ISSUE TITLE
[1.3.0.1] Count Bomb explosions remain on screen if interrupted by reading a Sign

### ISSUE THREAD

**Issue by MarsJenkar** [MegamixEngine/MegamixEngine#366]
Prerequisite:
A Count Bomb and a Sign object on the screen at the same time.  Obviously Mega Man has to be able to reach both.

Steps to replicate:
1. Activate the Count Bomb with Mega Man.
2. As the Count Bomb explodes, read the Sign object.

Expected result:
The explosion continues after Mega Man is done reading the sign.

Actual result:
The explosion freezes on screen.  Once Mega Man is done reading the sign, the explosion is still frozen.  Walking into the visible explosion does damage.

**Comment by MightyPrinny** [comment]
fixed in dev branch
