### ISSUE TITLE
[1.0.3.1m3] Devkit Miscellaneous Minor Missing Features

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#367]
Features that MAGMML2 levels made use of but MAGMML3 entrants can't. Ordered in what in my opinion are order of importance, greatest to least:
- [ ] Getting the player character's name and gender is not possible.
- [ ] Basic framing assets like the MAGMML3 logo. Very low priority as it is of use to few (and I'm not one of them), but they would serve as a fine reference. Also, Guts' Man's Asteroid. 'nuff said.

**Comment by MightyPrinny** [comment]
the first one wasn't a feature of the previous devkit the devteam had to edit the levels to show the current skin name

**Comment by sarysa** [comment]
Fair enough. Having it so players could do it properly themselves would alleviate the burden somewhat, but I understand where you're coming from.

Also, I've removed another entry as after discussing with pyro and learning it was an elevated/recycled feature from a specific MAGMML2 entry, it doesn't belong.

**Comment by ginger-mochi** [comment]
Closed as this is no longer relevant. (The MaGMML3 entry period has ended.)
