### ISSUE TITLE
Concrete Man Blocks

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#369]
Submitter: Splash
The Concrete Man Blocks that go up and down when you land on them have a bit of a problem. Normally, they respawn when you go offscreen and then go back onscreen. However, if they hit death spikes, then they just disappear until you die. To top it all off, it registers that the concrete block is supposed to have respawned - Ice Wall lands on the invisible space where it's supposed to be, for example.

**Comment by MightyPrinny** [comment]
already fixed in dev and magmml3-devkit branch
