### ISSUE TITLE
Tiles will not appear in Level

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#370]
Submitter: StarSoul
Email: starsoul1222@gmail.com
Whenever i load my level Tiles at the corner of the screen dont load properly the collision does

**Comment by StarSoul1234** [comment]
Im Using objSolid for collision

**Comment by MightyPrinny** [comment]
if you have flipped tiles remove them to make sure thats not the problem and please specify more, this is just too vague.

**Comment by StarSoul1234** [comment]
I do not have flipped Tiles but the problem only occurs when i use objVerticalScrolling on the right side of a wall It hasnt occured on the left side and only seems to happen with ObjVerticalScrolling since ive done it in other places and it works just fine

**Comment by MightyPrinny** [comment]
tiles have nothing to do with transitions, still not enough information,  upload a room with the problem or find the specific steps to reproduce the issue

**Comment by StarSoul1234** [comment]
[lvlGlitchProblem.zip](https://github.com/MegamixEngine/MegamixEngine/files/2463065/lvlGlitchProblem.zip)
If your a Magmml3 Judge dont look at this since its my Submission level

**Comment by MightyPrinny** [comment]
your tiles are overlapping in the same layer, only one of them will be drawn in game
