### ISSUE TITLE
Enemies with custom item drops will drop them every time they're killed

### ISSUE THREAD

**Issue by lnUniverse** [MegamixEngine/MegamixEngine#373]
If you set an enemy to have a custom drop, it will drop it every time it's killed. This is fine if that item is another enemy or a projectile, but it's not very good when the item is an E-tank, a Trickster Token, a key, or an Energy Element. 
I'd suggest all children of prtPickup should stop dropping after the first kill; any items that are important will persist between transitions anyways.

**Comment by sarysa** [comment]
This is somewhat of a related tangent, but it would be nice for destroyOnDeath to be extended to non-bosses. I've noticed the absence of this to be a common complaint in the judgeless Discord channels, and InUniverse's use case is just one of many.

**Comment by MightyPrinny** [comment]
the latest version of prtEntity has dropOnce

**Comment by snoruntpyro** [comment]
Idk why this is still open, new settings have been added to the dev branch for a while now.
