### ISSUE TITLE
Tornado Blow affecting objects rescaled through code (1.3.0.1m3)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#390]
Submitter: 128-Up
Objects with their image_xscale changed through create events or creation code have it forcibly reverted to -1 or 1 when Tornado Blow carries them away, regardless of what it was set to initially. Their image_yscale remains unaltered by Tornado Blow.

**Comment by snoruntpyro** [comment]
Fixed in dev branch.
