### ISSUE TITLE
Lightning Lord disappears when attached to cloud platforms

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#391]
Submitter: Diamond Wolf
(V1.0.3.1 Contest)
Rather than spawn in when "attachedToPlatform" is true, he just fails to ever spawn.
I looked at the code, and in the spawn event (user 15), it checks to see if the cloud it's attached to is visible and if it is sets its own dead variable to true, effectively meaning that it can't ever spawn since the only time it would spawn is when said cloud is visible.

**Comment by snoruntpyro** [comment]
Fixed in dev branch.
