### ISSUE TITLE
entityCanStep() is incomplete -> can break entities

### ISSUE THREAD

**Issue by RPGHacker** [MegamixEngine/MegamixEngine#395]
The function `entityCanStep()`, in its current form, is incomplete. This can lead to a rare, but severe, bug, when pausing the game with precise timing (or presumeably doing some other things that freeze the game).

This is the current implementation of entityCanStep():

```
return (!global.frozen && (!global.timeStopped || !stopOnFlash) && !dead && iceTimer <= 0);
```

This is correctly checking `global.frozen`, but does not check `self.frozen`, an instance variable each entity has. The correct implementation should look something like this:

```
return (!global.frozen && !self.frozen && (!global.timeStopped || !stopOnFlash) && !dead && iceTimer <= 0);
```

This might look harmless at first glance, but can actually mess up entities good because of this code in `objGlobalControl`:

```
/// freeze / unfreeze game objects
if (global.frozen)
{
    var len = array_length_1d(obj);
    for (i = 0; i < len; i += 1)
    {
        with (obj[i])
        {
            if (!frozen) // Start Freeze
            {
                pre_hsp = hspeed;
                pre_vsp = vspeed;
                pre_spe = speed;
                pre_isp = image_speed;
                hspeed = 0;
                vspeed = 0;
                speed = 0;
                image_speed = 0;
                frozen = 1;
            }
            
            for (_i = 0; _i <= 11; _i += 1)
            {
                if (alarm[_i] > 0)
                {
                    alarm[_i] += 1;
                }
            }
        }
    }
    setfrozen = 1;
}
else if (setfrozen) // Stop Freeze
{
    var len = array_length_1d(obj);
    for (i = 0; i < len; i += 1)
    {
        with (obj[i])
        {
            if (frozen)
            {
                hspeed = pre_hsp;
                vspeed = pre_vsp;
                speed = pre_spe;
                image_speed = pre_isp;
                frozen = 0;
            }
        }
    }
    setfrozen = 0;
}
```

Note how this code sets and clears `frozen`. The code modifies quite a few important variables of entities, so naturally if something goes wrong here, that can easily have severe consequences.

Now with the missing check in entityCanStep(), what happens is that entities can actually run their step logic for one frame before the unfreezing of objGlobalControl runs. Now let's assume before pausing the game, an entity's `image_speed` contained 0. This 0 was now copied to `pre_isp` by objGlobalControl. Now when unpausing the game, that entity's step logic would run for a frame and might immediately write another value to `image_speed`, let's say 0.5. Still harmless. However, shortly after that, objGlobalControl would run its unfreeze code and copy the 0 it previously backed up in `pre_isp` to `image_speed`, causing the entitiy`s animation to freeze in place entirely.

Now this condition isn't a problem for a lot of entities in the game, but it is pretty much guaranteed to mess up every single entity using an `Animation End` event without resetting its image_speed each frame, because the event will never be triggered and thus the entity will be stuck in its current state. Yet still for most entities that isn't a big problem. Projectiles will despawn once off-screen and enemies will reset once off-screen, undoing the bug for both of those. However, the bug also affects bosses, and you can't leave the screen while fighting a boss, so you can't reset a boss without dying. Now if said boss includes some kind of invulnerable phase and this bug occurs during that exact moment, the battle becomes unwinnable and the player will have to either die by pressing 2 or replay the entire level. This actually happened a couple of times with a boss I battled, which has an invincible teleportation move that requires the animation end event to transition to the next state. Having this bug occur here would make it impossible to damage the boss.

*REDACTED*

**Comment by RPGHacker** [comment]
Small addition to this: a lot of projectiles also seem to be affected by this. They usually don't use `entityCanStep()`, but use `!global.frozen` to check whether they should step. Instead, however, it should be something like `if (!global.frozen && !frozen)`.

One way I've experienced this bug in this regard was by pausing the game in the exact frame a buster projectile got reflected off of something. This caused the projectile to be frozen in place, since xspeed/yspeed are affected by this bug.

**Comment by ginger-mochi** [comment]
Thanks for the precise and clear explanation of this. This is a very pernicious issue that, so far as I'm aware, nobody else has noticed. However, I think it's actually a serious problem if `global.frozen` and `frozen` have different values during an entity's step. If we assume that `global.frozen` is only ever set/unset immediately prior to the instance-freezing code, then this problem disappears.

With that in mind, I think the correct solution here is actually to run the freezing code at the exact moment that `global.frozen` is set/unset. That way, `frozen` and `global.frozen` will never disagree, and in particular the animation glitch you mentioned won't occur.

So, we should just replace all instances of `global.frozen = true` and `global.frozen = false` with a call to a new script, `setGamePaused` (or similar), which sets `global.frozen` and then runs the code that is currently in the `objGlobalControl` step event.

**Comment by ginger-mochi** [comment]
Implemented MightyPrinny's suggestion of queueing the pause until the beginning of the frame, immediately prior to the entity-freezing logic in `objGlobalControl`. Commit f8e811ecab0c3dbe47ddbd0f3f6178ace8ab38ca.

With this change, `queuePause()` and `queueUnpause()` must be called in order to pause or unpause the game at the beginning of the next frame. Editing `global.frozen` directly will cause an assertion to fail at the beginning of the next frame, so don't do that.

I didn't find any logic which relied on same-frame pausing, not even in `objSectionSwitcher` or `objPauseMenu` (which were my greatest concerns).
