### ISSUE TITLE
LaJaBa despawns immediatrly after respawning

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#397]
Submitter: Fungus
Whoops! Forgot to say which version I am using. It's MegamixEngine-1.0.3.1m3
original bug report:
I put lajaba on the ground in my level. I playtest level. I walk towards where lajaba should be. He is not there. The script at bottom of game maker window says lajaba was spawned, but was then immediately despawned. Moving forward through level and then backtracking to where lajaba should have been will spawn him successfully.

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
