### ISSUE TITLE
Walking in Cossack Snow crashes game

### ISSUE THREAD

**Issue by TheBladeRoden** [MegamixEngine/MegamixEngine#400]
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object objMegaman:

Variable objMegaman.oilWalk(100167, -2147483648) not set before reading it.
 at gml_Script_playerHandleMovement (line 30) -                     xspeed = oilWalk * xDir;
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_playerHandleMovement (line 30)
called from - gml_Script_playerStep (line 13) -     playerHandleMovement();
called from - gml_Script_playerStepEventDefault (line 8) -     playerStep(); // General step event code
called from - gml_Object_objMegaman_StepNormalEvent_1 (line 7) -         playerStepEventDefault();

**Comment by snoruntpyro** [comment]
Please give more context. Are you on the Lightweight branch? This REALLY shouldn’t be a normal problem.

**Comment by TheBladeRoden** [comment]
I'm on magmml3-devkit

**Comment by snoruntpyro** [comment]
Fixed in dev branch.
