### ISSUE TITLE
LeverField's name is spelled wrong.

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#403]
Submitter: LeverField's name is spelled wrong.
Email: floating_clouds02@qq.com
The name of LeverField in 1.0.3 version is different from its version in 1.0.0.
In the 1.0.3 version, it is called "objLeverfield", but in the 1.0.0 version it is called "objLeverField".
I think this is due to spelling errors

**Comment by MightyPrinny** [comment]
already fixed
