### ISSUE TITLE
A ladder right after a sliding passage can make Mega Man clip through the ground

### ISSUE THREAD

**Issue by RPGHacker** [MegamixEngine/MegamixEngine#406]
If you place a ladder touching the ground directly after a sliding passage, then slide through the passage while holding up, Mega Man will immediately clip through the ground once touching the ladder. In my testing, I could reproduce this 100% of the time. The clipping did not occur when not holding up.

![Example setup](https://puu.sh/C5yhc/7b4b128cb0.png)

**Comment by ginger-mochi** [comment]
Additionally, this only happens if the solid below the ladder is exactly one tile thick. Currently investigating solutions.

**Comment by ginger-mochi** [comment]
In `playerHandleSliding`, coming out of a slide uses this:

`shiftObject(0,-gravDir,0);`

It doesn't check for collision. However, in `playerHandleClimbing`, it does:

`shiftObject(0,-gravDir,1);`

This seems to be the culprit. Fixed this in commit be340757.
