### ISSUE TITLE
[1.0.3.1] Fenix&Suzak: Killing the ascending bird will make the remaining one standstill, doing nothing.

### ISSUE THREAD

**Issue by NBlastMax** [MegamixEngine/MegamixEngine#409]
Route to reproduce:

1. Initiate Fenix and Suzak fight.
2. Severely damage one of the birds.
3. Finish off the one of the birds while it is ascending to attack. Best to use Spark Chaser.

Effect: Remaining bird will stay low-ground and will do nothing until killed.
Should be: Remaining bird attacks as usual.

**Comment by MightyPrinny** [comment]
I can't replicate this, are you sure you didn't modify the objects in some way?

**Comment by MightyPrinny** [comment]
fixed in dev branch
