### ISSUE TITLE
objMoveHover (GB I-IV) goes the wrong way sometimes, when shooting up close.

### ISSUE THREAD

**Issue by sarysa** [MegamixEngine/MegamixEngine#411]
If you get very close to objMoveHover, especially from its right, it'll often go the wrong way when shot. Even more common with charged shot. It might help if it checked the projectile's xspeed first to decide which way to go, I'm guessing it's checking its location instead.

**Comment by ginger-mochi** [comment]
Resolved by SpinAttaxx in 37680e07943fb2d0850d340cb72a14f29c65da36.
