### ISSUE TITLE
Odd error loading the engine

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#42]
Submitter: Javier Barragan Peña
Email: pipin95@hotmail.com
There are a couple errors, separate in 2 objects, one in objSkeltuppinPakkajoe, Event User Defined8, Action1 at Line7,Position 286:Wrong number of arguments to function or script. And in Object objUnitTestControl,Event Create, Action 1 at Line 16, Position 2: Wrong number of arguments to function or script. Not sure if its the engine or my game maker, using game maker 1.4.1567

**Comment by MightyPrinny** [comment]
1.4.1567 is not compatible with the engine, you have to update your copy of game maker studio.
