### ISSUE TITLE
Rush Cycle cannot save you from a killing blow

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#49]
Submitter: happygreenfrog
If you use Rush Cycle and get hit by an attack, then, if you're low enough on health that the attack would normally kill you, then Rush Cycle cannot prevent that damage from happening. Here's a GIF that demonstrates the issue in action: https://cdn.discordapp.com/attachments/466737266996543489/467027520017924097/RushBikeBug.gif

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
