### ISSUE TITLE
Push :: Execution Error - Variable Index

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#50]
Submitter: blackhook
FATAL ERROR in
action number 1
of Other Event: Room Start
for object objGlobalControl:

Push :: Execution Error - Variable Index [0,10] out of range [1,5] - -7.b(100003,10)
 at gml_Script_assert (line 21) -     b[5] = b[10]; // ASSERTION FAILED -- SEE CONSOLE
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_assert (line 21)
called from - gml_Object_objGlobalControl_StartRoomEvent_1 (line 38) - assert(!global.beginStageOnRoomBegin || global.inGame, "Began a stage but nowhere for player to spawn.");

Compile finished: 20:37:21

**Comment by snoruntpyro** [comment]
Please provide more details. What did you do to trigger this error?

**Comment by snoruntpyro** [comment]
It's been over a week with absolutely no clarification as to what this issue means so I'm closing it.
