### ISSUE TITLE
hotkey mistake.

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#55]
Submitter: _Tyra_
when I set my keys for the controls. the right control didn't work and it messed other stuff up and it accidentally combined with another key so I couldn't change it. could you please add a function to automatically set them to default out of the settings. thanks if you do

**Comment by snoruntpyro** [comment]
This is prevented in version 0.9.3 (you can't set multiple inputs to the same button anymore), however we didn't add a reset to default setting.
