### ISSUE TITLE
Bubble Man's Lingering Bullets

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#56]
Submitter: BigRockerEnding
Whenever Bubble Man begins to fly/float up, he leaves behind what looks a white dot that never moves or disappears but is able to damage Mega Man, making me assume that it might be one of Bubble Man's bullets that happens to be lingering in place. This occurs regardless of whether or not Bubble Man is underwater.

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
