### ISSUE TITLE
Grey Devil Issues

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#58]
Submitter: BigRockerEnding
Email: bigrockerending@gmail.com
If Mega Man takes contact damage from Grey Devil, a damage popup will not appear, even if they're enabled, and Mega Man's I-Frames will wear off as soon as he recovers from knockback. In addition, certain special solid objects, such as boss doors, won't make Grey Devil come out of his blob form when he reaches them, making him impossible to beat due to his unhittable state.

**Comment by MegamixEngine** [comment]
The contact damage glitch has been fixed. Not sure about boss doors.

**Comment by MightyPrinny** [comment]
fixed in dev branch
