### ISSUE TITLE
Non-existant gundrill

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#62]
Submitter: Your Main Man Scoobert
Email: noah73182@gmail.com
The devkit works fine until I try to open my level, at which point I get this error:
 ERROR in
action number 1
for object objGundrillCover:

Tile does not exist.
at gml_Object_objGundrillCover_CreateEvent_1 (line 20) -         tileBG[tileNumber] = tile_get_background(myTile);
the enemies in my level are GSQ, top fiend, teckyun, and kamapot spawner. I did remove kamapot spawner and tried again, but I still couldn't open my level.

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
