### ISSUE TITLE
Volt Man crashes the game if his shield gets despawned (Version 0.8.1 Beta)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#70]
Submitter: Yoshiatom
It's possible to despawn Volt Man's shield if he's in a scrolling room, and it's possible for him to attempt to fire the non-existant sheild, which crashes the game. Volt Man himself also behaves oddly while off-screen, often constantly making the same sound effect.

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object objVoltMan:

Unable to find any instance for object index '871' name 'objVoltBarrier'
 at gml_Object_objVoltMan_StepNormalEvent_1 (line 132) -                     VS = instance_create(objVoltBarrier.x, objVoltBarrier.y,
############################################################################################

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
