### ISSUE TITLE
Morning Joe + Water Shield crash (0.9.1)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#71]
Submitter: William W.
Email: jwandzw@gmail.com
Using the Water Shield on the projectiles thrown by Morning Joe (Challenger From the Future) crashes the game with this error:

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object objMorningJoe:

Unable to find any instance for object index '108163'
 at gml_Object_objMorningJoe_StepNormalEvent_1 (line 66) -             star[3].newX = x + 80 * image_xscale;
############################################################################################

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
