### ISSUE TITLE
Hover sprites not reloading (0.9.2)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#77]
Submitter: William W.
Email: jwandzw@gmail.com
A specific set of actions can cause a graphical glitch with the Hover object (Objects > Gimmicks > MM4 > objHover). I made this happen by despawning the Hover normally (standing on it and then letting it make contact with a wall), walking away so that the Hover's starting position was no longer on the screen, then walking back to where the Hover spawned. The Hover object itself had respawned (its collision and function were working correctly), but the object's sprites did not load correctly, making it appear invisible.

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
