### ISSUE TITLE
Gemini Laser collision issues 

### ISSUE THREAD

**Issue by TheRealParmaJon** [MegamixEngine/MegamixEngine#79]
1. When next to a wall and you fire gemini laser it goes through the wall and it seems like in some corners it also clips through as well.  https://imgur.com/a/6fh9mzy

2. When firing at a wall at a certain distance only half the laser is reflected and half goes through the wall. https://imgur.com/a/Fm9PAoS

3. Sometimes it goes over tiles at certain distances https://imgur.com/3ORVB8m

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
