### ISSUE TITLE
Pharaohman clipped through wall

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#83]
Submitter: Mmmmmmmmmmmmmmmmm
In the Example Game, upon entering the Pharaohman boss room and making said boss jump around fighting him, he clipped through the rightmost wall and instantly died. He did not provide any energy element and I was forced to retry the fight. I unfortunately was not able to reproduce the bug in subsequent fights.

I am playing Version 0.9.2 (beta) on Normal difficulty. I had previously defeated Honey Woman and Plant Man, and did attempt using Hornet Chaser on the boss, though I had switched back to the Mega buster before the clip occurred.

**Comment by snoruntpyro** [comment]
Fixed in 0.9.4.
