### ISSUE TITLE
left contol problem (slightly fixed in the recent update - 0.9.2 beta)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#88]
Submitter: _Tyra_
Email: Alfiehawtin@hotmail.com
when playing my level and try to go left, it doesn't work and reseting the controls doesn't help either. however I can go left if I spam the M.blade which I have to confuse it to turn me the other way and I must keep shooting or keep hold of the left button to move. when I let go, mega man will stop and turn right but not move. this was partially fixed in 0.9.2 but I think the problem is made by the default control settings.

**Comment by MightyPrinny** [comment]
Closing since you fixed it and it didn't seem to be a problem with the engine
