### ISSUE TITLE
Attempting to configure gamepad softlocks the game (Version 0.9.2 Beta)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#89]
Submitter: Yoshiatom
When to you go to change the gamepad controls in the options, when you get to Previous Weapon (P1) the game refuses to procede, any button you press will only make the menu move sound effect and nothing else, since there's no way to back out of setting up the controller it's effectivley a softlock. I tested this with various directInput controllers.

On another note I think the controller support could be improved; most D-pads don't seem to work and default Xinput bindings don't match MaGMML2's. (Triggers instead of bumpers for switching weapons and MaGMML2 lets you use both B and Y to slide, while this engine only lets you use Y)

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
