### ISSUE TITLE
MM9 Fake Man + MM10 Endless Tilesets

### ISSUE THREAD

**Issue by Flashman85** [MegamixEngine/MegamixEngine#90]
Could someone please add these tilesets and their animations (MM9 Fake Man, MM10 Endless) to the devkit?

![tstfakeman](https://user-images.githubusercontent.com/35474492/42727872-211f30ce-877c-11e8-9600-c2fbf99ee52b.png)

![tstfakemananimated](https://user-images.githubusercontent.com/35474492/42727874-23654f94-877c-11e8-8441-a11dfb576470.png)

![tstmm10endlessv1](https://user-images.githubusercontent.com/35474492/42730245-ce3527e6-87bd-11e8-938d-c32cc820b05b.png)

![tstmm10endlessanimated](https://user-images.githubusercontent.com/35474492/42730246-cf51cc06-87bd-11e8-8567-b23e482e6d40.png)

**Comment by snoruntpyro** [comment]
Added in version 0.9.3.
