### ISSUE TITLE
Various Quick Lighting graphical glitches (0.9.2)

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#94]
Submitter: William W.
Email: jwandzw@gmail.com
When Quick Lighting lights up a room, several objects will suddenly turn invisible. From testing most enemies in the devkit, I found the following turn invisible when a room has been brightened by Quick Lighting:
-Menu text (this includes both the pause menu and the debug menu)
-The "READY" text upon starting a stage
-The glowing ends of Spark Chaser
-The crosshairs created by Homing Sniper
-The text popups created by Skeletup n' Pakkajoe
-The electricity shot out by Electric Gabyoalls
-The white parts of Kemumakin clouds (sprKemumakinCloud1)
-Pointan projectile outlines (sprPointanSelectionSquare)

**Comment by snoruntpyro** [comment]
Fixed in version 0.9.3.
